// Scalar API Reference, brandeado con tokens MATCHPOINT (verde primary,
// Plus Jakarta Sans headings, Inter body, sidebar negro tipo dashboard,
// radios y sombras MP). theme: "none" para construir desde cero y que las
// vars custom no pelean con un preset.
import Script from "next/script";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "MATCHPOINT API · Docs",
  description: "Internal + external API reference, autogenerated from Zod schemas.",
};

// Tokens MP traducidos a las CSS vars que expone Scalar. Light por defecto;
// las vars `--scalar-color-1/2/3` van de más oscuro (texto principal) a más
// claro (texto terciario). `--scalar-background-1/2/3` igual pero para fondos.
const MP_CUSTOM_CSS = `
  :root {
    /* Brand */
    --scalar-color-1: #0a0a0a;
    --scalar-color-2: #3f3f46;
    --scalar-color-3: #737373;
    --scalar-color-accent: #10b981;

    --scalar-background-1: #ffffff;
    --scalar-background-2: #fafafa;
    --scalar-background-3: #f5f5f5;
    --scalar-background-accent: rgba(16, 185, 129, 0.08);

    --scalar-border-color: #e5e5e5;

    /* Botón primary */
    --scalar-button-1: #10b981;
    --scalar-button-1-hover: #059669;
    --scalar-button-1-color: #ffffff;

    /* Method colors (HTTP verbs) — alineados a paleta MP */
    --scalar-color-green: #10b981;
    --scalar-color-red: #dc2626;
    --scalar-color-yellow: #f59e0b;
    --scalar-color-blue: #0ea5e9;
    --scalar-color-orange: #f97316;
    --scalar-color-purple: #7c3aed;

    /* Tipografía */
    --scalar-font: "Inter", ui-sans-serif, system-ui, sans-serif;
    --scalar-font-code: ui-monospace, "SF Mono", Menlo, monospace;
    --scalar-heading-1: "Plus Jakarta Sans", ui-sans-serif, system-ui, sans-serif;
    --scalar-heading-2: "Plus Jakarta Sans", ui-sans-serif, system-ui, sans-serif;

    /* Bordes redondeados consistentes con .card del dashboard */
    --scalar-radius: 10px;
    --scalar-radius-lg: 14px;
    --scalar-radius-xl: 18px;

    /* Sombras MP */
    --scalar-shadow-1: 0 1px 3px rgba(0, 0, 0, 0.04);
    --scalar-shadow-2: 0 4px 12px rgba(0, 0, 0, 0.05);
  }

  /* Sidebar oscuro tipo dashboard MP */
  .sidebar {
    --scalar-sidebar-background-1: #09090b !important;
    --scalar-sidebar-item-hover-background: #18181b !important;
    --scalar-sidebar-item-active-background: rgba(16, 185, 129, 0.15) !important;
    --scalar-sidebar-color-1: #ffffff !important;
    --scalar-sidebar-color-2: #a1a1aa !important;
    --scalar-sidebar-color-active: #10b981 !important;
    --scalar-sidebar-border-color: #27272a !important;
    --scalar-sidebar-search-background: #18181b !important;
    --scalar-sidebar-search-color: #ffffff !important;
    --scalar-sidebar-search-border-color: #3f3f46 !important;
  }

  /* Tipografía: headings con Plus Jakarta Sans, peso 900, tracking apretado */
  .section-header,
  h1, h2, h3 {
    font-family: "Plus Jakarta Sans", ui-sans-serif, system-ui, sans-serif !important;
    font-weight: 900 !important;
    letter-spacing: -0.02em !important;
  }

  /* Verde MP en el "dot" final estilo "MATCHPOINT." de la landing */
  .scalar-app .scalar-api-reference h1::after {
    content: ".";
    color: #10b981;
  }

  /* Botones primary (Send, Try it) con verde MP y press scale */
  button[class*="scalar-button-primary"],
  .scalar-button-primary {
    background: #10b981 !important;
    color: #ffffff !important;
    border-radius: 9999px !important;
    font-weight: 800 !important;
    letter-spacing: 0.04em !important;
    text-transform: uppercase !important;
    transition: transform 160ms cubic-bezier(0.23, 1, 0.32, 1),
                background 160ms cubic-bezier(0.23, 1, 0.32, 1) !important;
  }
  button[class*="scalar-button-primary"]:hover,
  .scalar-button-primary:hover {
    background: #059669 !important;
  }
  button[class*="scalar-button-primary"]:active,
  .scalar-button-primary:active {
    transform: scale(0.97);
  }

  /* Cards / paneles con bordes y sombras MP */
  .scalar-card,
  [class*="scalar-card"] {
    border-radius: 14px !important;
    border: 1px solid #e5e5e5 !important;
  }

  /* HTTP method pills más punchy, igual peso que dashboard pills */
  .method,
  [class*="http-method"] {
    font-family: "Inter", sans-serif !important;
    font-weight: 900 !important;
    letter-spacing: 0.1em !important;
    text-transform: uppercase !important;
  }

  /* Body antialiased como el resto de la app */
  body, .scalar-app {
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
  }

  /* Scrollbars finos */
  ::-webkit-scrollbar {
    width: 10px;
    height: 10px;
  }
  ::-webkit-scrollbar-thumb {
    background: #d4d4d4;
    border-radius: 6px;
  }
  ::-webkit-scrollbar-thumb:hover {
    background: #a1a1aa;
  }
`;

export default function DocsPage() {
  return (
    <>
      {/* Font preload — Scalar carga las suyas sino; nosotros injectamos las MP. */}
      <link
        rel="preconnect"
        href="https://fonts.googleapis.com"
      />
      <link
        rel="preconnect"
        href="https://fonts.gstatic.com"
        crossOrigin=""
      />
      <link
        rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800;900&family=Inter:wght@400;500;600;700;800;900&display=swap"
      />
      <div
        id="api-reference"
        data-url="/openapi.json"
        data-configuration={JSON.stringify({
          theme: "none",
          layout: "modern",
          hideClientButton: false,
          defaultHttpClient: { targetKey: "javascript", clientKey: "fetch" },
          metaData: { title: "MATCHPOINT API Docs" },
          authentication: {
            preferredSecurityScheme: "cookieAuth",
          },
          customCss: MP_CUSTOM_CSS,
        })}
      />
      <Script
        src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"
        strategy="afterInteractive"
      />
    </>
  );
}
