// Scalar API Reference UI, served from /docs.
// Uses the Scalar standalone CDN script (no extra npm dep, no React-version friction).
// The spec is the static /openapi.json generated by `pnpm openapi:build`.
//
// Access policy:
//   - MP_DOCS_PUBLIC=true  → open to anyone
//   - MP_DOCS_PUBLIC=false → require an admin session (handled by proxy/server gate later)
// For now the page renders unconditionally to make wiring easy in local dev.

import Script from "next/script";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "MatchPoint API · Docs",
  description: "Internal + external API reference, autogenerated from Zod schemas.",
};

export default function DocsPage() {
  return (
    <>
      <div
        id="api-reference"
        data-url="/openapi.json"
        data-configuration={JSON.stringify({
          theme: "default",
          layout: "modern",
          hideClientButton: false,
          defaultHttpClient: { targetKey: "javascript", clientKey: "fetch" },
          metaData: { title: "MatchPoint API Docs" },
          authentication: {
            preferredSecurityScheme: "cookieAuth",
          },
        })}
      />
      <Script
        src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"
        strategy="afterInteractive"
      />
    </>
  );
}
