// Generates public/openapi.json from the Zod schema registry.
// Run with: pnpm openapi:build  (or npm run openapi:build)
//
// Triggered by:
//   - local dev when editing schemas / routes (manual)
//   - CI on every PR (--check mode would diff for breakage; out of scope here)
//
// Why this file is a script and not a Next route: we want the spec on disk
// in /public so it's served as a static asset and consumed by Scalar UI
// without re-running the registry on every page load.

import { mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { OpenApiGeneratorV31 } from "@asteasolutions/zod-to-openapi";

import { registry } from "../src/lib/api/openapi/registry";
import "../src/lib/api/openapi/paths";

const generator = new OpenApiGeneratorV31(registry.definitions);

const document = generator.generateDocument({
  openapi: "3.1.0",
  info: {
    title: "MatchPoint API",
    version: process.env.npm_package_version ?? "0.1.0",
    description:
      "Pickleball / Tennis / Padel platform — internal + external API. " +
      "Schemas autogenerated from Zod (single source of truth). " +
      "See docs/architecture/60-openapi.md.",
    contact: { name: "MatchPoint", url: "https://matchpoint.app" },
  },
  servers: [
    { url: "http://localhost:3000", description: "Local" },
    { url: "https://staging.matchpoint.dev", description: "Staging" },
    { url: "https://app.matchpoint.dev", description: "Production" },
  ],
  tags: [
    { name: "Auth", description: "Sign up / sign in / sign out / switch role" },
    { name: "Profile", description: "Current user profile and session" },
    { name: "Clubs", description: "Public listings + owner management" },
    { name: "ClubApplications", description: "Solicitar Club wizard (5 steps + review pipeline)" },
    { name: "Courts" },
    { name: "Reservations" },
    { name: "CheckIns" },
    { name: "Cash" },
    { name: "ProShop" },
    { name: "Coaches" },
    { name: "Classes" },
    { name: "Students" },
    { name: "Resources" },
    { name: "Messaging" },
    { name: "Friends" },
    { name: "Teams" },
    { name: "Ranking" },
    { name: "Tournaments" },
    { name: "Events" },
    { name: "Notifications", description: "Role-aware in-app + push + email feed" },
    { name: "Broadcasts" },
    { name: "Moderation" },
    { name: "Support" },
    { name: "FeatureFlags" },
    { name: "Partners" },
    { name: "Webhooks" },
  ],
});

const outDir = resolve(process.cwd(), "public");
mkdirSync(outDir, { recursive: true });
const outPath = resolve(outDir, "openapi.json");
writeFileSync(outPath, JSON.stringify(document, null, 2));

const pathCount = Object.keys(document.paths ?? {}).length;
const schemaCount = Object.keys(document.components?.schemas ?? {}).length;
console.log(`✓ public/openapi.json written — ${pathCount} paths, ${schemaCount} schemas`);
