-- Restaura catálogo notification_kinds ausente por drift de migraciones.
-- Sin filas aquí, fn_enqueue_notification falla con "unknown notification kind".

insert into notification_kinds (kind, description, allowed_roles, default_channels, category) values
  ('role_request_new', 'Nueva solicitud de rol recibida', array['admin']::mp_role[], array['inapp']::mp_notification_channel[], 'roles'),
  ('role_request_approved', 'Tu solicitud de rol fue aprobada', array['user','partner','owner','manager','coach','employee']::mp_role[], array['inapp','email']::mp_notification_channel[], 'roles'),
  ('role_request_rejected', 'Tu solicitud de rol fue rechazada', array['user','partner','owner','manager','coach','employee']::mp_role[], array['inapp','email']::mp_notification_channel[], 'roles'),
  ('club_application_new', 'Nueva solicitud de club', array['admin']::mp_role[], array['inapp']::mp_notification_channel[], 'clubs'),
  ('club_application_approved', 'Tu solicitud de club fue aprobada', array['user','owner']::mp_role[], array['inapp','email']::mp_notification_channel[], 'clubs'),
  ('club_application_rejected', 'Tu solicitud de club fue rechazada', array['user']::mp_role[], array['inapp','email']::mp_notification_channel[], 'clubs'),
  ('club_application_status', 'Estado de tu solicitud de club', array['user']::mp_role[], array['inapp']::mp_notification_channel[], 'clubs'),
  ('reservation_created', 'Reserva confirmada', array['user']::mp_role[], array['inapp']::mp_notification_channel[], 'reservations'),
  ('reservation_cancelled', 'Reserva cancelada', array['user']::mp_role[], array['inapp']::mp_notification_channel[], 'reservations'),
  ('ticket_new', 'Nuevo ticket de soporte', array['admin']::mp_role[], array['inapp']::mp_notification_channel[], 'support'),
  ('ticket_assigned', 'Te asignaron un ticket de soporte', array['admin']::mp_role[], array['inapp']::mp_notification_channel[], 'support'),
  ('friend_request_new', 'Tienes una nueva solicitud de amistad', array['user']::mp_role[], array['inapp']::mp_notification_channel[], 'social'),
  ('broadcast', 'Mensaje masivo enviado por MATCHPOINT', array['user','admin','partner','owner','manager','coach','employee']::mp_role[], array['inapp']::mp_notification_channel[], 'marketing'),
  ('payment_captured', 'Pago confirmado por administración', array['user']::mp_role[], array['inapp']::mp_notification_channel[], 'pagos'),
  ('mp_plus_activated', 'MATCHPOINT+ activado', array['user']::mp_role[], array['inapp']::mp_notification_channel[], 'premium'),
  ('mp_plus_revoked', 'MATCHPOINT+ desactivado', array['user']::mp_role[], array['inapp']::mp_notification_channel[], 'premium'),
  ('refund_completed', 'Reembolso registrado', array['user']::mp_role[], array['inapp']::mp_notification_channel[], 'pagos'),
  ('report_resolved', 'Reporte revisado por moderación', array['user']::mp_role[], array['inapp']::mp_notification_channel[], 'moderation'),
  ('role_assigned', 'Rol asignado', array['admin','partner','user','owner','manager','coach','employee']::mp_role[], array['inapp']::mp_notification_channel[], 'roles'),
  ('role_revoked', 'Rol revocado', array['admin','partner','user','owner','manager','coach','employee']::mp_role[], array['inapp']::mp_notification_channel[], 'roles'),
  ('club_staff_assigned', 'Personal agregado a un club', array['manager','coach','employee']::mp_role[], array['inapp']::mp_notification_channel[], 'roles'),
  ('club_staff_removed', 'Personal removido de un club', array['manager','coach','employee']::mp_role[], array['inapp']::mp_notification_channel[], 'roles'),
  ('welcome_owner', 'Bienvenida al portal del club', array['owner']::mp_role[], array['inapp']::mp_notification_channel[], 'clubs'),
  ('plan_expiring_soon', 'Tu plan premium expira pronto', array['user']::mp_role[], array['inapp']::mp_notification_channel[], 'premium'),
  ('match_cancelled', 'Partido cancelado', array['user']::mp_role[], array['inapp']::mp_notification_channel[], 'matches'),
  ('match_rescheduled', 'Partido reprogramado', array['user']::mp_role[], array['inapp']::mp_notification_channel[], 'matches'),
  ('match_no_show_reported', 'Te reportaron inasistencia', array['user']::mp_role[], array['inapp']::mp_notification_channel[], 'matches'),
  ('match_challenge_received', 'Nuevo desafío de partido', array['user']::mp_role[], array['inapp']::mp_notification_channel[], 'matches'),
  ('tournament_rescheduled', 'Torneo reprogramado', array['user','partner']::mp_role[], array['inapp']::mp_notification_channel[], 'tournaments'),
  ('tournament_cancelled', 'Torneo cancelado', array['user','partner']::mp_role[], array['inapp']::mp_notification_channel[], 'tournaments'),
  ('registration_accepted', 'Inscripción aceptada', array['user']::mp_role[], array['inapp']::mp_notification_channel[], 'tournaments'),
  ('registration_rejected', 'Inscripción rechazada', array['user']::mp_role[], array['inapp']::mp_notification_channel[], 'tournaments'),
  ('tournament_registration_removed', 'Inscripción removida', array['user']::mp_role[], array['inapp']::mp_notification_channel[], 'tournaments'),
  ('tournament_published', 'Torneo abierto a inscripciones', array['partner']::mp_role[], array['inapp']::mp_notification_channel[], 'tournaments'),
  ('tournament_finished', 'Torneo finalizado', array['user']::mp_role[], array['inapp']::mp_notification_channel[], 'tournaments'),
  ('tournament_registration_new', 'Nueva inscripción en tu torneo', array['partner','owner','manager']::mp_role[], array['inapp']::mp_notification_channel[], 'tournaments'),
  ('payment_proof_rejected', 'Comprobante de pago rechazado', array['user']::mp_role[], array['inapp']::mp_notification_channel[], 'pagos'),
  ('payment_proof_approved', 'Comprobante de pago aprobado', array['user']::mp_role[], array['inapp']::mp_notification_channel[], 'pagos'),
  ('event_rescheduled', 'Evento reprogramado', array['user']::mp_role[], array['inapp']::mp_notification_channel[], 'events'),
  ('event_registration_cancelled', 'Inscripción a evento cancelada', array['user']::mp_role[], array['inapp']::mp_notification_channel[], 'events')
on conflict (kind) do update set
  description = excluded.description,
  allowed_roles = excluded.allowed_roles,
  default_channels = excluded.default_channels,
  category = excluded.category;
