-- Admin sponsors: catálogo, inventario de slots, placements y tracking básico.
-- Lectura pública solo vía vista curada; las tablas crudas quedan admin-only.

create table if not exists public.sponsors (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  status text not null default 'active' check (status in ('active', 'paused', 'archived')),
  website_url text,
  logo_url text,
  brand_color text,
  contact_name text,
  contact_email text,
  billing_email text,
  contract_starts_on date,
  contract_ends_on date,
  notes text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint sponsors_slug_format_chk check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint sponsors_brand_color_chk check (brand_color is null or brand_color ~ '^#[0-9A-Fa-f]{6}$'),
  constraint sponsors_contract_dates_chk check (
    contract_starts_on is null
    or contract_ends_on is null
    or contract_ends_on >= contract_starts_on
  )
);

create table if not exists public.sponsor_slots (
  id uuid primary key default gen_random_uuid(),
  key text not null unique,
  surface text not null,
  label text not null,
  description text,
  max_active_placements int not null default 1 check (max_active_placements > 0),
  base_price_cents int not null default 0 check (base_price_cents >= 0),
  currency text not null default 'USD',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint sponsor_slots_key_format_chk check (key ~ '^[a-z0-9]+(?:_[a-z0-9]+)*$')
);

create table if not exists public.sponsor_placements (
  id uuid primary key default gen_random_uuid(),
  sponsor_id uuid not null references public.sponsors(id) on delete cascade,
  slot_id uuid not null references public.sponsor_slots(id) on delete restrict,
  status text not null default 'draft' check (status in ('draft', 'active', 'paused', 'archived')),
  headline text not null,
  body text,
  image_url text,
  image_alt text,
  target_url text,
  priority int not null default 0,
  starts_at timestamptz not null default now(),
  ends_at timestamptz,
  contract_amount_cents int not null default 0 check (contract_amount_cents >= 0),
  currency text not null default 'USD',
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint sponsor_placements_dates_chk check (ends_at is null or ends_at > starts_at)
);

create table if not exists public.sponsor_placement_events (
  id bigint generated by default as identity primary key,
  placement_id uuid not null references public.sponsor_placements(id) on delete cascade,
  event_type text not null check (event_type in ('impression', 'click')),
  user_id uuid references public.profiles(id) on delete set null,
  session_id text,
  pathname text,
  referrer text,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);

create index if not exists sponsor_placements_slot_status_idx
  on public.sponsor_placements(slot_id, status, starts_at, ends_at);
create index if not exists sponsor_placements_sponsor_idx
  on public.sponsor_placements(sponsor_id);
create index if not exists sponsor_placement_events_placement_type_idx
  on public.sponsor_placement_events(placement_id, event_type, occurred_at desc);
create index if not exists sponsor_placement_events_occurred_idx
  on public.sponsor_placement_events(occurred_at desc);

drop trigger if exists tg_sponsors_updated_at on public.sponsors;
create trigger tg_sponsors_updated_at
  before update on public.sponsors
  for each row execute function public.tg_set_updated_at();

drop trigger if exists tg_sponsor_slots_updated_at on public.sponsor_slots;
create trigger tg_sponsor_slots_updated_at
  before update on public.sponsor_slots
  for each row execute function public.tg_set_updated_at();

drop trigger if exists tg_sponsor_placements_updated_at on public.sponsor_placements;
create trigger tg_sponsor_placements_updated_at
  before update on public.sponsor_placements
  for each row execute function public.tg_set_updated_at();

alter table public.sponsors enable row level security;
alter table public.sponsor_slots enable row level security;
alter table public.sponsor_placements enable row level security;
alter table public.sponsor_placement_events enable row level security;

drop policy if exists sponsors_admin_all on public.sponsors;
create policy sponsors_admin_all on public.sponsors
  for all using (public.mp_is_admin())
  with check (public.mp_is_admin());

drop policy if exists sponsor_slots_admin_all on public.sponsor_slots;
create policy sponsor_slots_admin_all on public.sponsor_slots
  for all using (public.mp_is_admin())
  with check (public.mp_is_admin());

drop policy if exists sponsor_placements_admin_all on public.sponsor_placements;
create policy sponsor_placements_admin_all on public.sponsor_placements
  for all using (public.mp_is_admin())
  with check (public.mp_is_admin());

drop policy if exists sponsor_placement_events_admin_select on public.sponsor_placement_events;
create policy sponsor_placement_events_admin_select on public.sponsor_placement_events
  for select using (public.mp_is_admin());

-- Las inserciones de tracking pasan por server action + service role. No hay
-- policy de INSERT pública para evitar abuso directo sobre la tabla de eventos.

create or replace view public.active_sponsor_placements
with (security_barrier = true) as
select
  p.id as placement_id,
  sl.key as slot_key,
  sl.surface,
  sl.label as slot_label,
  p.priority,
  p.headline,
  p.body,
  p.image_url,
  p.image_alt,
  p.target_url,
  p.starts_at,
  p.ends_at,
  s.id as sponsor_id,
  s.name as sponsor_name,
  s.slug as sponsor_slug,
  s.logo_url as sponsor_logo_url,
  s.website_url as sponsor_website_url,
  s.brand_color as sponsor_brand_color
from public.sponsor_placements p
join public.sponsors s on s.id = p.sponsor_id
join public.sponsor_slots sl on sl.id = p.slot_id
where p.status = 'active'
  and s.status = 'active'
  and sl.is_active
  and p.starts_at <= now()
  and (p.ends_at is null or p.ends_at > now());

grant select on public.active_sponsor_placements to anon, authenticated;

insert into public.sponsor_slots (key, surface, label, description, max_active_placements, base_price_cents)
values
  ('dashboard_user_home', 'dashboard', 'Inicio jugador', 'Tarjeta patrocinada en el home del jugador.', 1, 0),
  ('tournaments_listing', 'tournaments', 'Listado de torneos', 'Placement visible cerca de torneos destacados y próximos eventos.', 2, 0),
  ('clubs_listing', 'clubs', 'Listado de clubes', 'Placement visible en exploración de clubes.', 1, 0),
  ('ranking_sidebar', 'ranking', 'Ranking', 'Placement lateral en ranking y superficies de competencia.', 1, 0),
  ('payment_confirmation', 'payments', 'Confirmación de pago', 'Mensaje de sponsor después de flujos de comprobante o pago registrado.', 1, 0)
on conflict (key) do nothing;

drop trigger if exists tg_audit_sponsors on public.sponsors;
create trigger tg_audit_sponsors after insert or update or delete on public.sponsors
  for each row execute function public.tg_audit();

drop trigger if exists tg_audit_sponsor_slots on public.sponsor_slots;
create trigger tg_audit_sponsor_slots after insert or update or delete on public.sponsor_slots
  for each row execute function public.tg_audit();

drop trigger if exists tg_audit_sponsor_placements on public.sponsor_placements;
create trigger tg_audit_sponsor_placements after insert or update or delete on public.sponsor_placements
  for each row execute function public.tg_audit();

do $$
declare
  _table text;
  _tables text[] := array[
    'sponsors',
    'sponsor_slots',
    'sponsor_placements',
    'sponsor_placement_events'
  ];
begin
  foreach _table in array _tables loop
    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = _table
    ) then
      execute format('alter publication supabase_realtime add table public.%I', _table);
    end if;
  end loop;
end $$;
