-- Help CMS: artículos, revisiones, feedback y búsqueda.
-- Edición admin-only; lectura autenticada solo de contenido publicado.

do $$
begin
  create type public.help_article_status as enum ('draft', 'published', 'archived');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type public.help_content_kind as enum ('article', 'video', 'glossary');
exception when duplicate_object then null;
end $$;

create table if not exists public.help_articles (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title text not null,
  excerpt text,
  category_key text not null,
  category_label text not null,
  icon text,
  status public.help_article_status not null default 'draft',
  content_kind public.help_content_kind not null default 'article',
  content jsonb not null default '[]'::jsonb,
  tags text[] not null default '{}'::text[],
  reading_minutes int not null default 3 check (reading_minutes between 1 and 120),
  video_url text,
  video_duration_label text,
  glossary_term text,
  is_featured boolean not null default false,
  sort_order int not null default 0,
  view_count int not null default 0 check (view_count >= 0),
  helpful_count int not null default 0 check (helpful_count >= 0),
  not_helpful_count int not null default 0 check (not_helpful_count >= 0),
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null,
  published_by uuid references public.profiles(id) on delete set null,
  archived_by uuid references public.profiles(id) on delete set null,
  published_at timestamptz,
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  search_vector tsvector not null default ''::tsvector,
  constraint help_articles_slug_format_chk check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint help_articles_content_array_chk check (jsonb_typeof(content) = 'array'),
  constraint help_articles_video_url_chk check (content_kind <> 'video' or video_url is not null),
  constraint help_articles_glossary_term_chk check (content_kind <> 'glossary' or glossary_term is not null)
);

create table if not exists public.help_article_revisions (
  id uuid primary key default gen_random_uuid(),
  article_id uuid not null references public.help_articles(id) on delete cascade,
  revision_no int not null,
  status public.help_article_status not null,
  title text not null,
  excerpt text,
  content_kind public.help_content_kind not null,
  content jsonb not null,
  snapshot jsonb not null,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (article_id, revision_no)
);

create table if not exists public.help_feedback (
  id uuid primary key default gen_random_uuid(),
  article_id uuid not null references public.help_articles(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  helpful boolean not null,
  comment text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (article_id, user_id)
);

create table if not exists public.help_search_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  query text not null,
  category_key text,
  results_count int not null default 0 check (results_count >= 0),
  created_at timestamptz not null default now(),
  constraint help_search_logs_query_len_chk check (char_length(trim(query)) between 2 and 160)
);

create index if not exists help_articles_status_category_idx
  on public.help_articles(status, category_key, sort_order, published_at desc);
create index if not exists help_articles_kind_status_idx
  on public.help_articles(content_kind, status, published_at desc);
create index if not exists help_articles_featured_idx
  on public.help_articles(is_featured, status, sort_order)
  where is_featured;
create index if not exists help_articles_search_idx
  on public.help_articles using gin(search_vector);
create index if not exists help_article_revisions_article_idx
  on public.help_article_revisions(article_id, revision_no desc);
create index if not exists help_feedback_article_idx
  on public.help_feedback(article_id, created_at desc);
create index if not exists help_search_logs_misses_idx
  on public.help_search_logs(results_count, created_at desc)
  where results_count = 0;

create or replace function public.tg_help_articles_search_vector()
returns trigger
language plpgsql
as $$
begin
  new.search_vector :=
    to_tsvector(
      'spanish',
      coalesce(new.title, '') || ' ' ||
      coalesce(new.excerpt, '') || ' ' ||
      coalesce(new.category_label, '') || ' ' ||
      array_to_string(new.tags, ' ') || ' ' ||
      coalesce(new.glossary_term, '') || ' ' ||
      new.content::text
    );
  return new;
end;
$$;

drop trigger if exists tg_help_articles_search_vector on public.help_articles;
create trigger tg_help_articles_search_vector
  before insert or update of title, excerpt, category_label, tags, glossary_term, content
  on public.help_articles
  for each row execute function public.tg_help_articles_search_vector();

drop trigger if exists tg_help_articles_updated_at on public.help_articles;
create trigger tg_help_articles_updated_at
  before update on public.help_articles
  for each row execute function public.tg_set_updated_at();

drop trigger if exists tg_help_feedback_updated_at on public.help_feedback;
create trigger tg_help_feedback_updated_at
  before update on public.help_feedback
  for each row execute function public.tg_set_updated_at();

alter table public.help_articles enable row level security;
alter table public.help_article_revisions enable row level security;
alter table public.help_feedback enable row level security;
alter table public.help_search_logs enable row level security;

drop policy if exists help_articles_published_select on public.help_articles;
create policy help_articles_published_select on public.help_articles
  for select to authenticated
  using (status = 'published');

drop policy if exists help_articles_admin_all on public.help_articles;
create policy help_articles_admin_all on public.help_articles
  for all using (public.mp_is_admin())
  with check (public.mp_is_admin());

drop policy if exists help_article_revisions_admin_all on public.help_article_revisions;
create policy help_article_revisions_admin_all on public.help_article_revisions
  for all using (public.mp_is_admin())
  with check (public.mp_is_admin());

drop policy if exists help_feedback_admin_select on public.help_feedback;
create policy help_feedback_admin_select on public.help_feedback
  for select using (public.mp_is_admin());

drop policy if exists help_feedback_user_select_own on public.help_feedback;
create policy help_feedback_user_select_own on public.help_feedback
  for select to authenticated
  using (user_id = auth.uid());

drop policy if exists help_feedback_user_insert_own on public.help_feedback;
create policy help_feedback_user_insert_own on public.help_feedback
  for insert to authenticated
  with check (
    user_id = auth.uid()
    and exists (
      select 1 from public.help_articles a
      where a.id = article_id
        and a.status = 'published'
    )
  );

drop policy if exists help_feedback_user_update_own on public.help_feedback;
create policy help_feedback_user_update_own on public.help_feedback
  for update to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

drop policy if exists help_search_logs_admin_select on public.help_search_logs;
create policy help_search_logs_admin_select on public.help_search_logs
  for select using (public.mp_is_admin());

drop policy if exists help_search_logs_user_insert on public.help_search_logs;
create policy help_search_logs_user_insert on public.help_search_logs
  for insert to authenticated
  with check (user_id = auth.uid());

create or replace function public.help_record_article_view(p_article_id uuid)
returns int
language plpgsql
security definer
set search_path = public
as $$
declare
  _views int;
begin
  if auth.uid() is null then
    raise exception 'AUTH.UNAUTHENTICATED' using errcode = '28000';
  end if;

  update public.help_articles
  set view_count = view_count + 1
  where id = p_article_id
    and status = 'published'
  returning view_count into _views;

  if _views is null then
    raise exception 'HELP.ARTICLE_NOT_FOUND' using errcode = '22023';
  end if;

  return _views;
end;
$$;

revoke all on function public.help_record_article_view(uuid) from public;
grant execute on function public.help_record_article_view(uuid) to authenticated;

drop trigger if exists tg_audit_help_articles on public.help_articles;
create trigger tg_audit_help_articles after insert or update or delete on public.help_articles
  for each row execute function public.tg_audit();

drop trigger if exists tg_audit_help_article_revisions on public.help_article_revisions;
create trigger tg_audit_help_article_revisions after insert or update or delete on public.help_article_revisions
  for each row execute function public.tg_audit();

do $$
declare
  _table text;
  _tables text[] := array[
    'help_articles',
    'help_article_revisions',
    'help_feedback',
    'help_search_logs'
  ];
begin
  foreach _table in array _tables loop
    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = _table
    ) then
      execute format('alter publication supabase_realtime add table public.%I', _table);
    end if;
  end loop;
end $$;
